sudo: required

services:
  - docker

script:
  - docker run -v $(pwd):/mnt --rm -t -e COPR_USERNAME=${COPR_USERNAME} -e COPR_LOGIN=${COPR_LOGIN} -e COPR_TOKEN=${COPR_TOKEN} fedora:rawhide /mnt/build

deploy:
  provider: releases
  api_key:
    secure: P9DMEvTxBIUZ/0beJIhdBA7M4YfV1/AN9EoIP485IMR/zich42jh2h3W6vB7V2BSvNBvOBruGJwJbGDzKMqShyyut/Az8gare7uA/+9tkRrAR6RcX7Q7FvqLJyTMIDOfjkEjtCR+Mu3nK8szb0qWKWwQe6a4r3jjYUk6n2TkBI6Q/rCS9Tm9omemT/DH44F+akwCjzlSaUwN6I+LRKv75REKfPK0wzMEiIq/b3gzXc/nWopxpIPEVMw9RpfnrPvVmYit4whnI6Po1SKwfim74C0pi9zB2ZciAN3BpvrR6TKpjF+VQRK5IojqDA8Uu0RqWk4Eqvo4U7MWfC5m+hN69Mggu/xdP/crqX3Bf1qNXRoR2UXKlIxEUkP3jCxwtDnlqktAbf+PHwSAj/Rqpq6BBta+1U3nzbr61VVuTksKjTWjvoWUuN0DBsOUn9iZED+NInzR/ceN/YRiKKUdtEoKCTRXrkKsQ1GHNhIG5CEJeGpMCI3CjkpGGrBt8TaMw7N2ZWILvZV5DRUPsnofx4QgUBwkh7sn7VistyD0afBqLiUa+FAsw88FjSWERKAs8VJVch0TI+UjVRVGkMRQmB+tWQSzxat1arq7V17p2kwjYUIYHcY3K0L0y/1MqE7fjt3wqP86Z6nA5UzqxRRMDmkibefu2RXm+fsoucNJ5/enFq8=
  file: "*.rpm"
  on:
    repo: sspreitzer/test
