sudo: required
services:
- docker
script:
- docker run -v $(pwd):/mnt --rm -t -e COPR_USERNAME=${COPR_USERNAME} -e COPR_LOGIN=${COPR_LOGIN}
  -e COPR_TOKEN=${COPR_TOKEN} fedora:rawhide /mnt/build
deploy:
  skip_cleanup: true
  file_glob: true
  provider: releases
  api_key:
    secure: FtCVgp1BtVLj1HV/1TWnX7nAOzImLB17ix5NBDSFUdZ682xIjXUGstwTgbyC8lO/TmNuGXIYm/fW2OjL4NkKPpYFa1FpSYor9JlC8gimV9giLse4cLqaMR5Lwdwvfh4ks0e+IgIpcJZno+6BBTcU74cvJE65L4RTnESXq6cMkm59+5nOH7ls9XHBYusJDQfbv/KM+ntNHD6yIPZd3FkRVz0fVO4a/x1lWjJteKZ0SBytXlNJ6YpxCmrpEe7fhNfzH1kfZqGMaenwIB4eIZUwo/Vs6gsEcMJRnYLxNDbiR194YNOpOwMw7/mgFAn18VGK6XSkkjJ+69PNhq6cYggbNFZT9AW0XmekcgwhNUq4kPlOfuhT2a7MXIapiA8FgiqjdZYOQUhkTz7ksqBEguNIuYaw8mqoIKNBw8rnXDvZyypy3jdB8rwFskSbHQ5uAEx/3Y+zO9bRH8hc3L2bkLPOgda+tPPLGA/ul7XFeBKWd7+Bnf/M6cCO+M60pdseKLqAKnwhKTpmjQg9IHMKvzNJuqdDYgX4LmIuIESzRhLIj6nyaebd3EmUTkbo0wo06JiK1fZBltXaAIM7eNi77VsHlMBcXtkxotVc4bgoMREghQvi32XFmYQEXO1USEqSKLlIGcw++vwgnOlp/zK6KU2iM8Gk+fsW00lcqoKOXm1btec=
  file: "*.rpm"
  on:
    tags: true
